addressbook/config/routes.rb
Addressbook::Application.routes.draw do
  root 'contacts#index'

  get "contacts/search" => 'contacts#search'
  get "contacts/:id/favourite" => 'contacts#favourite', as: 'favourite_contact'
  resources :contacts

  

end

addressbook/app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, presence: true
  validates_format_of :email,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
  validates_format_of :phone, :with => /[0-9\s]*/
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

addressbook/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contacts = Contact.order(name: :asc)
  end

  def search
    @contacts = Contact.where('name like ?', "#{params[:q]}%" )
    render 'index'
  end

  def new 
    @contact = Contact.new
  end

  def create
    @contact = Contact.new contact_params
    
    if @contact.save
      redirect_to action: 'index', controller: 'contacts', id: @contact.id
    else 
      @errors = @contact.errors.full_messages
      render 'new'
    end
  end

  def edit
    @contact = Contact.find(params[:id])
  end 

  def update
    @contact = Contact.find params[:id]
    if @contact.update_attributes contact_params
      redirect_to contact_path(@contact)
    else
      @errors = @contact.error.full_messages
      render 'edit'
    end
  end
  
  def favourite
    @contact = Contact.find params[:id]
    @contact.favourite = !@contact.favourite
    @contact.save
    render 'show'
  end

  def destroy
    contact = Contact.find(params[:id])
    contact.destroy
    redirect_to contacts_path
  end

  def show
    @contact = Contact.find(params[:id])
  end

  private
    def contact_params
         params.require(:contact).permit(:name, :phone, :email, :address, :avatar) 
    end 
end

addressbook/app/helpers/contacts_helper.rb
module ContactsHelper
end

addressbook/app/views/contacts/_form.html.erb
<% if @contact.errors.any? %>
  <ul>
    <% @contact.errors.full_messages.each do |error_msg| %>
      <li><%= error_msg %></li>
    <% end %>
  </ul>
<% end %>

  <%= form_for @contact, :html=>{:multipart => true} do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :phone %>
  <%= f.text_field :phone %>
  <br>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <br>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <br>
  <%= f.label :avatar %>
  <%= f.file_field :avatar %>
  <%= f.submit 'Save' %>
<% end %>

addressbook/app/views/contacts/create.html.erb
<h1>Contacts#create</h1>
<p>Find me in app/views/contacts/create.html.erb</p>

addressbook/app/views/contacts/destroy.html.erb
<h1>Contacts#destroy</h1>
<p>Find me in app/views/contacts/destroy.html.erb</p>

addressbook/app/views/contacts/edit.html.erb
<h2> Update Contact</h2>
<%= render "form" %>

addressbook/app/views/contacts/index.html.erb
<h1>My Contacts</h1>
<%= form_tag("/contacts/search", method: "get") do %>
  <%= label_tag(:q, "Search for:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %>
<ul class="collection"> 
  <% @contacts.each do |contact| %> 
    <li class="collection-item materialize-red.lighten-5">
      <% if contact.favourite %>
        <i class="fa fa-star fa-lg"></i>
      <% end %>    
      <strong><%= link_to contact.name, contact_path(contact.id) %></strong>  
    <%= link_to('Delete', contact_path(contact), method: :delete, confirm: 'Are you sure?') %>  </li>
  <% end %> 
</ul> 
<%= link_to("Add Contact", new_contact_path, class: "waves-effect waves-light btn") %>
<a href="/contacts/new">Add Contact</a>
<i class="material-icons left"></i>

addressbook/app/views/contacts/new.html.erb
<%= render "form" %>

addressbook/app/views/contacts/show.html.erb
<h1>My friend <%= @contact.name %></h1>

<div class="card">
	<%= image_tag @contact.avatar.url(:medium) %>
	<dl>
		<dt>Address: </dt>
		<dd><%= @contact.address %></dd>
		<dt>Phone number: </dt>
		<dd><%= @contact.phone %></dd>
		<dt>Email: </dt>
		<dd><%= @contact.email %></dd>
	</dl>
</div>
<%= link_to "Edit", edit_contact_path(@contact),  class: 'waves-effect waves-light btn'  %>
<% if @contact.favourite %>
	<i class="fa fa-star fa-lg"></i>
<% else %>
	<%= link_to "Favourite", favourite_contact_path(@contact),  class: 'waves-effect waves-light btn'  %>
<% end %>

addressbook/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Addressbook</title>

  <%= stylesheet_link_tag    "application", media: "all" %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.0/css/materialize.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <%= javascript_include_tag "application"  %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="row center">
      <%= yield %>
    </div>
  </div>
</body>
</html>